apiVersion: v1
kind: Pod

metadata:
  name: food-app-pod
  namespace: food-app

  labels:
    app: food-app

spec:
  containers:
  - name: food-app-container
    image: harshithareddy24/food-app:v1

    ports:
    - containerPort: 80