apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "food-app.fullname" . }}
  labels:
    app: {{ include "food-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "food-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "food-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
      volumes:
        - name: {{ .Values.volume.name }}
          emptyDir: {}
